swagger: "2.0"
info:
  title: "ERP API"
  version: "1.0"
basePath: /erp
tags:
- name: User Maintenance
- name: Product Management
- name: Requistion Management
- name: Agent Management
- name: Product Subcategory Management
- name: Main Provider Management
- name: Analyst Management
- name: Provider Product Relationship
- name: Global
- name: Document Management
- name: Provider Management
- name: Requisition Management
- name: GeneralServices Management
- name: Notification Maintenance
- name: Document History Management
- name: User Management
- name: Tracking Number Process
- name: Warehouse Management
- name: Permission Management
- name: Brand Management
- name: Access Management
- name: User Access
- name: Product Prices Management
- name: Product Category Management
paths:
  /login/:
    $ref: erp_modules/users/login.yaml
  /v5.1/users/{user_id}:
    get:
      $ref: erp_modules/v5_1_user/get_user.yaml
  /v5.2/users/{user_id}:
    get:
      $ref: erp_modules/v5_2_user/get_user.yaml
  /v5.6/apis/type_computers/all:
    get:
      $ref: erp_modules/v5_6_general_services/get_type_computers.yaml
  /v5.6/api/type_services/all:
    get:
      $ref: erp_modules/v5_6_general_services/get_type_services.yaml
  /v5.6/apis/users/get_session:
    get:
      $ref: erp_modules/v5_6_user/get_session.yaml
  /v5.6/apis/users/{user_id}:
    get:
      $ref: erp_modules/v5_6_user/get_user.yaml
