"""empty message

Revision ID: 6582cb95987e
Revises: 
Create Date: 2022-02-10 20:58:48.226765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6582cb95987e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_components',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_components_id'), 'brand_components', ['id'], unique=False)
    op.create_table('brand_laptops',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_laptops_id'), 'brand_laptops', ['id'], unique=False)
    op.create_table('instant_users',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instant_users_id'), 'instant_users', ['id'], unique=False)
    op.create_table('oauth_clients',
    sa.Column('name', sa.String(length=40), nullable=True, comment='OAuth Client Name'),
    sa.Column('client_id', sa.String(length=40), nullable=False, comment='OAuth Client ID'),
    sa.Column('client_secret', sa.String(length=55), nullable=False, comment='OAuth Client Secret'),
    sa.Column('client_type', sa.String(length=20), server_default='public', nullable=True, comment='OAuth Client Type'),
    sa.Column('_redirect_uris', sa.Text(), nullable=True, comment='OAuth Client Redirect URI'),
    sa.Column('default_scope', sa.Text(), server_default='email address', nullable=True, comment='OAuth Client Default Scope'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('type_computers',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_computers_id'), 'type_computers', ['id'], unique=False)
    op.create_table('type_services',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_services_id'), 'type_services', ['id'], unique=False)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('core_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('cpus',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('brand_component_id', sa.Integer(), nullable=False, comment='brand_components ID'),
    sa.ForeignKeyConstraint(['brand_component_id'], ['brand_components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpus_id'), 'cpus', ['id'], unique=False)
    op.create_table('graphic_cards',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('brand_component_id', sa.Integer(), nullable=False, comment='brand_components ID'),
    sa.ForeignKeyConstraint(['brand_component_id'], ['brand_components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graphic_cards_id'), 'graphic_cards', ['id'], unique=False)
    op.create_table('minimal_type_services',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_service_id', sa.Integer(), nullable=False, comment='type_services ID'),
    sa.ForeignKeyConstraint(['type_service_id'], ['type_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minimal_type_services_id'), 'minimal_type_services', ['id'], unique=False)
    op.create_table('model_laptops',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('brand_laptop_id', sa.Integer(), nullable=False, comment='brand_laptops ID'),
    sa.ForeignKeyConstraint(['brand_laptop_id'], ['brand_laptops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_laptops_id'), 'model_laptops', ['id'], unique=False)
    op.create_table('oauth_grants',
    sa.Column('id', sa.Integer(), nullable=False, comment='OAuth Grant ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='User ID'),
    sa.Column('client_id', sa.String(length=40), nullable=False, comment='OAuth Client ID'),
    sa.Column('code', sa.String(length=255), nullable=False, comment='OAuth Grant Code'),
    sa.Column('redirect_uri', sa.String(length=255), nullable=True, comment='OAuth Grant Redirect URI'),
    sa.Column('scope', sa.Text(), nullable=True, comment='OAuth Grant Scope'),
    sa.Column('expires', sa.DateTime(), nullable=True, comment='OAuth Grant Expire Time'),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False, comment='OAuth Token ID'),
    sa.Column('client_id', sa.String(length=40), nullable=False, comment='OAuth Client ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='User ID'),
    sa.Column('token_type', sa.String(length=40), nullable=True, comment='OAuth Token Type'),
    sa.Column('access_token', sa.String(length=255), nullable=True, comment='OAuth Access Token'),
    sa.Column('refresh_token', sa.String(length=255), nullable=True, comment='OAuth Refresh Token'),
    sa.Column('expires', sa.DateTime(), nullable=True, comment='OAuth Token Expire Time'),
    sa.Column('scope', sa.Text(), nullable=True, comment='OAuth Token Scope'),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_defective_components',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('min_amount', sa.Integer(), nullable=False),
    sa.Column('max_amount', sa.Integer(), nullable=False),
    sa.Column('type_computer_id', sa.Integer(), nullable=False, comment='type_computers ID'),
    sa.ForeignKeyConstraint(['type_computer_id'], ['type_computers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_defective_components_id'), 'type_defective_components', ['id'], unique=False)
    op.create_table('user_deliveries',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('instant_user_id', sa.Integer(), nullable=False, comment='instant_users ID'),
    sa.ForeignKeyConstraint(['instant_user_id'], ['instant_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_deliveries_id'), 'user_deliveries', ['id'], unique=False)
    op.create_table('services',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('type_computer_id', sa.Integer(), nullable=False, comment='type_computers ID'),
    sa.Column('minimal_type_service_id', sa.Integer(), nullable=False, comment='minimal_type_services ID'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['minimal_type_service_id'], ['minimal_type_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_computer_id'], ['type_computers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_table('type_sub_services',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('type_service_id', sa.Integer(), nullable=False, comment='type_services ID'),
    sa.Column('minimal_type_service_id', sa.Integer(), nullable=False, comment='minimal_type_services ID'),
    sa.ForeignKeyConstraint(['minimal_type_service_id'], ['minimal_type_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_service_id'], ['type_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_sub_services_id'), 'type_sub_services', ['id'], unique=False)
    op.create_table('user_laptop_datas',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_repaired', sa.Boolean(), nullable=False),
    sa.Column('is_repowered', sa.Boolean(), nullable=False),
    sa.Column('model_laptop_id', sa.Integer(), nullable=False, comment='model_laptops ID'),
    sa.Column('laptop_request_name', sa.String(length=180), nullable=True),
    sa.ForeignKeyConstraint(['model_laptop_id'], ['model_laptops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_laptop_datas_id'), 'user_laptop_datas', ['id'], unique=False)
    op.create_table('user_pc_datas',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operating_system', sa.String(length=180), nullable=False),
    sa.Column('vram_quantity', sa.Integer(), nullable=False),
    sa.Column('ram_quantity', sa.Integer(), nullable=False),
    sa.Column('cpu_id', sa.Integer(), nullable=False, comment='cpus ID'),
    sa.Column('graphic_card_id', sa.Integer(), nullable=False, comment='graphic_cards ID'),
    sa.Column('gpu_request_name', sa.String(length=180), nullable=True),
    sa.Column('cpu_request_name', sa.String(length=180), nullable=True),
    sa.ForeignKeyConstraint(['cpu_id'], ['cpus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graphic_card_id'], ['graphic_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_pc_datas_id'), 'user_pc_datas', ['id'], unique=False)
    op.create_table('user_requests',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instant_user_id', sa.Integer(), nullable=False, comment='instant_users ID'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='services ID'),
    sa.Column('user_pc_data_id', sa.Integer(), nullable=True, comment='user_pc_datas ID'),
    sa.Column('user_laptop_data_id', sa.Integer(), nullable=True, comment='user_laptop_datas ID'),
    sa.ForeignKeyConstraint(['instant_user_id'], ['instant_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_laptop_data_id'], ['user_laptop_datas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_pc_data_id'], ['user_pc_datas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_requests_id'), 'user_requests', ['id'], unique=False)
    op.create_table('user_request_defective_components',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_request_id', sa.Integer(), nullable=False, comment='user_requests ID'),
    sa.Column('type_defective_component_id', sa.Integer(), nullable=False, comment='type_defective_components ID'),
    sa.ForeignKeyConstraint(['type_defective_component_id'], ['type_defective_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_request_id'], ['user_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_request_defective_components_id'), 'user_request_defective_components', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_request_defective_components_id'), table_name='user_request_defective_components')
    op.drop_table('user_request_defective_components')
    op.drop_index(op.f('ix_user_requests_id'), table_name='user_requests')
    op.drop_table('user_requests')
    op.drop_index(op.f('ix_user_pc_datas_id'), table_name='user_pc_datas')
    op.drop_table('user_pc_datas')
    op.drop_index(op.f('ix_user_laptop_datas_id'), table_name='user_laptop_datas')
    op.drop_table('user_laptop_datas')
    op.drop_index(op.f('ix_type_sub_services_id'), table_name='type_sub_services')
    op.drop_table('type_sub_services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_user_deliveries_id'), table_name='user_deliveries')
    op.drop_table('user_deliveries')
    op.drop_index(op.f('ix_type_defective_components_id'), table_name='type_defective_components')
    op.drop_table('type_defective_components')
    op.drop_table('oauth_tokens')
    op.drop_table('oauth_grants')
    op.drop_index(op.f('ix_model_laptops_id'), table_name='model_laptops')
    op.drop_table('model_laptops')
    op.drop_index(op.f('ix_minimal_type_services_id'), table_name='minimal_type_services')
    op.drop_table('minimal_type_services')
    op.drop_index(op.f('ix_graphic_cards_id'), table_name='graphic_cards')
    op.drop_table('graphic_cards')
    op.drop_index(op.f('ix_cpus_id'), table_name='cpus')
    op.drop_table('cpus')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_type_services_id'), table_name='type_services')
    op.drop_table('type_services')
    op.drop_index(op.f('ix_type_computers_id'), table_name='type_computers')
    op.drop_table('type_computers')
    op.drop_table('oauth_clients')
    op.drop_index(op.f('ix_instant_users_id'), table_name='instant_users')
    op.drop_table('instant_users')
    op.drop_index(op.f('ix_brand_laptops_id'), table_name='brand_laptops')
    op.drop_table('brand_laptops')
    op.drop_index(op.f('ix_brand_components_id'), table_name='brand_components')
    op.drop_table('brand_components')
    # ### end Alembic commands ###
