"""empty message

Revision ID: 72bf7921fe21
Revises: 
Create Date: 2022-02-26 04:12:22.005924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bf7921fe21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_details',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('is_company', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_details_id'), 'billing_details', ['id'], unique=False)
    op.create_table('brand_components',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_components_id'), 'brand_components', ['id'], unique=False)
    op.create_table('brand_laptops',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_laptops_id'), 'brand_laptops', ['id'], unique=False)
    op.create_table('category_peripherals',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_peripherals_id'), 'category_peripherals', ['id'], unique=False)
    op.create_table('category_programs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_programs_id'), 'category_programs', ['id'], unique=False)
    op.create_table('computer_cost_ranges',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('range_cost', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_computer_cost_ranges_id'), 'computer_cost_ranges', ['id'], unique=False)
    op.create_table('instant_users',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('type_work', sa.Integer(), nullable=False),
    sa.Column('for_purchase', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instant_users_id'), 'instant_users', ['id'], unique=False)
    op.create_table('oauth_clients',
    sa.Column('name', sa.String(length=40), nullable=True, comment='OAuth Client Name'),
    sa.Column('client_id', sa.String(length=40), nullable=False, comment='OAuth Client ID'),
    sa.Column('client_secret', sa.String(length=55), nullable=False, comment='OAuth Client Secret'),
    sa.Column('client_type', sa.String(length=20), server_default='public', nullable=True, comment='OAuth Client Type'),
    sa.Column('_redirect_uris', sa.Text(), nullable=True, comment='OAuth Client Redirect URI'),
    sa.Column('default_scope', sa.Text(), server_default='email address', nullable=True, comment='OAuth Client Default Scope'),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('type_computers',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_computers_id'), 'type_computers', ['id'], unique=False)
    op.create_table('type_services',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_services_id'), 'type_services', ['id'], unique=False)
    op.create_table('use_type_pcs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_use_type_pcs_id'), 'use_type_pcs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('core_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('billing_detail_companies',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ruc', sa.String(length=20), nullable=False),
    sa.Column('business_name', sa.String(length=180), nullable=False),
    sa.Column('billing_detail_id', sa.Integer(), nullable=False, comment='billing_details ID'),
    sa.ForeignKeyConstraint(['billing_detail_id'], ['billing_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_detail_companies_id'), 'billing_detail_companies', ['id'], unique=False)
    op.create_table('billing_detail_natural_persons',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dni', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('billing_detail_id', sa.Integer(), nullable=False, comment='billing_details ID'),
    sa.ForeignKeyConstraint(['billing_detail_id'], ['billing_details.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_detail_natural_persons_id'), 'billing_detail_natural_persons', ['id'], unique=False)
    op.create_table('budget_pcs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('use_type_pc_id', sa.Integer(), nullable=False, comment='use_type_pcs ID'),
    sa.ForeignKeyConstraint(['use_type_pc_id'], ['use_type_pcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_pcs_id'), 'budget_pcs', ['id'], unique=False)
    op.create_table('cpus',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('brand_component_id', sa.Integer(), nullable=False, comment='brand_components ID'),
    sa.ForeignKeyConstraint(['brand_component_id'], ['brand_components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpus_id'), 'cpus', ['id'], unique=False)
    op.create_table('graphic_cards',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('brand_component_id', sa.Integer(), nullable=False, comment='brand_components ID'),
    sa.ForeignKeyConstraint(['brand_component_id'], ['brand_components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graphic_cards_id'), 'graphic_cards', ['id'], unique=False)
    op.create_table('minimal_type_services',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_service_id', sa.Integer(), nullable=False, comment='type_services ID'),
    sa.ForeignKeyConstraint(['type_service_id'], ['type_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minimal_type_services_id'), 'minimal_type_services', ['id'], unique=False)
    op.create_table('model_laptops',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('brand_laptop_id', sa.Integer(), nullable=False, comment='brand_laptops ID'),
    sa.ForeignKeyConstraint(['brand_laptop_id'], ['brand_laptops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_laptops_id'), 'model_laptops', ['id'], unique=False)
    op.create_table('oauth_grants',
    sa.Column('id', sa.Integer(), nullable=False, comment='OAuth Grant ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='User ID'),
    sa.Column('client_id', sa.String(length=40), nullable=False, comment='OAuth Client ID'),
    sa.Column('code', sa.String(length=255), nullable=False, comment='OAuth Grant Code'),
    sa.Column('redirect_uri', sa.String(length=255), nullable=True, comment='OAuth Grant Redirect URI'),
    sa.Column('scope', sa.Text(), nullable=True, comment='OAuth Grant Scope'),
    sa.Column('expires', sa.DateTime(), nullable=True, comment='OAuth Grant Expire Time'),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False, comment='OAuth Token ID'),
    sa.Column('client_id', sa.String(length=40), nullable=False, comment='OAuth Client ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='User ID'),
    sa.Column('token_type', sa.String(length=40), nullable=True, comment='OAuth Token Type'),
    sa.Column('access_token', sa.String(length=255), nullable=True, comment='OAuth Access Token'),
    sa.Column('refresh_token', sa.String(length=255), nullable=True, comment='OAuth Refresh Token'),
    sa.Column('expires', sa.DateTime(), nullable=True, comment='OAuth Token Expire Time'),
    sa.Column('scope', sa.Text(), nullable=True, comment='OAuth Token Scope'),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peripherals',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=180), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_rgb', sa.Boolean(), nullable=True),
    sa.Column('category_peripheral_id', sa.Integer(), nullable=False, comment='category_peripherals ID'),
    sa.ForeignKeyConstraint(['category_peripheral_id'], ['category_peripherals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peripherals_id'), 'peripherals', ['id'], unique=False)
    op.create_table('programs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_program_id', sa.Integer(), nullable=False, comment='category_programs ID'),
    sa.ForeignKeyConstraint(['category_program_id'], ['category_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    op.create_table('type_defective_components',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('type_computer_id', sa.Integer(), nullable=False, comment='type_computers ID'),
    sa.ForeignKeyConstraint(['type_computer_id'], ['type_computers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_defective_components_id'), 'type_defective_components', ['id'], unique=False)
    op.create_table('user_deliveries',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('instant_user_id', sa.Integer(), nullable=False, comment='instant_users ID'),
    sa.ForeignKeyConstraint(['instant_user_id'], ['instant_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_deliveries_id'), 'user_deliveries', ['id'], unique=False)
    op.create_table('accessories',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attributes', sa.Text(), nullable=False),
    sa.Column('peripheral_id', sa.Integer(), nullable=False, comment='peripherals ID'),
    sa.ForeignKeyConstraint(['peripheral_id'], ['peripherals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessories_id'), 'accessories', ['id'], unique=False)
    op.create_table('cameras',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resolution', sa.String(length=100), nullable=False),
    sa.Column('output', sa.String(length=100), nullable=False),
    sa.Column('peripheral_id', sa.Integer(), nullable=False, comment='peripherals ID'),
    sa.ForeignKeyConstraint(['peripheral_id'], ['peripherals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_table('cost_range_defective_components',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('range_price_component', sa.String(length=180), nullable=False),
    sa.Column('computer_cost_range_id', sa.Integer(), nullable=False, comment='computer_cost_ranges ID'),
    sa.Column('type_defective_component_id', sa.Integer(), nullable=False, comment='type_defective_components ID'),
    sa.ForeignKeyConstraint(['computer_cost_range_id'], ['computer_cost_ranges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_defective_component_id'], ['type_defective_components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_range_defective_components_id'), 'cost_range_defective_components', ['id'], unique=False)
    op.create_table('headsets',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sound', sa.String(length=100), nullable=False),
    sa.Column('microphone', sa.Boolean(), nullable=False),
    sa.Column('output', sa.String(length=100), nullable=False),
    sa.Column('peripheral_id', sa.Integer(), nullable=False, comment='peripherals ID'),
    sa.ForeignKeyConstraint(['peripheral_id'], ['peripherals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_headsets_id'), 'headsets', ['id'], unique=False)
    op.create_table('keyboards',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('switch', sa.String(length=100), nullable=True),
    sa.Column('output', sa.String(length=100), nullable=False),
    sa.Column('peripheral_id', sa.Integer(), nullable=False, comment='peripherals ID'),
    sa.ForeignKeyConstraint(['peripheral_id'], ['peripherals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyboards_id'), 'keyboards', ['id'], unique=False)
    op.create_table('kit_mouse_keyboards',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_keyboard', sa.String(length=100), nullable=False),
    sa.Column('output_keyboard', sa.String(length=100), nullable=False),
    sa.Column('peripheral_id', sa.Integer(), nullable=False, comment='peripherals ID'),
    sa.ForeignKeyConstraint(['peripheral_id'], ['peripherals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kit_mouse_keyboards_id'), 'kit_mouse_keyboards', ['id'], unique=False)
    op.create_table('monitors',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('panel', sa.String(length=50), nullable=False),
    sa.Column('resolution', sa.String(length=100), nullable=False),
    sa.Column('response_time', sa.String(length=50), nullable=False),
    sa.Column('screen_size', sa.String(length=100), nullable=False),
    sa.Column('hdr', sa.String(length=50), nullable=True),
    sa.Column('peripheral_id', sa.Integer(), nullable=False, comment='peripherals ID'),
    sa.ForeignKeyConstraint(['peripheral_id'], ['peripherals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitors_id'), 'monitors', ['id'], unique=False)
    op.create_table('mouses',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sensor', sa.String(length=100), nullable=False),
    sa.Column('dpi', sa.String(length=50), nullable=False),
    sa.Column('colour', sa.String(length=100), nullable=True),
    sa.Column('peripheral_id', sa.Integer(), nullable=False, comment='peripherals ID'),
    sa.ForeignKeyConstraint(['peripheral_id'], ['peripherals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mouses_id'), 'mouses', ['id'], unique=False)
    op.create_table('pc_specifications',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('ranking', sa.DECIMAL(precision=2, scale=1), nullable=False),
    sa.Column('cpu_name', sa.String(length=180), nullable=False),
    sa.Column('gpu_name', sa.String(length=180), nullable=True),
    sa.Column('ram_name', sa.String(length=180), nullable=False),
    sa.Column('storage', sa.String(length=180), nullable=False),
    sa.Column('case', sa.String(length=180), nullable=False),
    sa.Column('psu_name', sa.String(length=180), nullable=False),
    sa.Column('budget_pc_id', sa.Integer(), nullable=False, comment='budget_pcs ID'),
    sa.ForeignKeyConstraint(['budget_pc_id'], ['budget_pcs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pc_specifications_id'), 'pc_specifications', ['id'], unique=False)
    op.create_table('psus',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('power', sa.String(length=50), nullable=False),
    sa.Column('peripheral_id', sa.Integer(), nullable=False, comment='peripherals ID'),
    sa.ForeignKeyConstraint(['peripheral_id'], ['peripherals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psus_id'), 'psus', ['id'], unique=False)
    op.create_table('services',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.String(length=10), nullable=True),
    sa.Column('type_computer_id', sa.Integer(), nullable=False, comment='type_computers ID'),
    sa.Column('minimal_type_service_id', sa.Integer(), nullable=False, comment='minimal_type_services ID'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['minimal_type_service_id'], ['minimal_type_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_computer_id'], ['type_computers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_table('speakers',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subwoofer', sa.String(length=50), nullable=False),
    sa.Column('satellite_speaker', sa.String(length=50), nullable=False),
    sa.Column('peripheral_id', sa.Integer(), nullable=False, comment='peripherals ID'),
    sa.ForeignKeyConstraint(['peripheral_id'], ['peripherals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speakers_id'), 'speakers', ['id'], unique=False)
    op.create_table('type_sub_services',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('type_service_id', sa.Integer(), nullable=False, comment='type_services ID'),
    sa.Column('minimal_type_service_id', sa.Integer(), nullable=False, comment='minimal_type_services ID'),
    sa.ForeignKeyConstraint(['minimal_type_service_id'], ['minimal_type_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_service_id'], ['type_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_sub_services_id'), 'type_sub_services', ['id'], unique=False)
    op.create_table('user_laptop_datas',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_repaired', sa.Boolean(), nullable=False),
    sa.Column('is_repowered', sa.Boolean(), nullable=False),
    sa.Column('model_laptop_id', sa.Integer(), nullable=False, comment='model_laptops ID'),
    sa.Column('laptop_request_name', sa.String(length=180), nullable=True),
    sa.ForeignKeyConstraint(['model_laptop_id'], ['model_laptops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_laptop_datas_id'), 'user_laptop_datas', ['id'], unique=False)
    op.create_table('user_pc_datas',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operating_system', sa.String(length=180), nullable=False),
    sa.Column('vram_quantity', sa.String(length=12), nullable=False),
    sa.Column('ram_quantity', sa.String(length=12), nullable=False),
    sa.Column('cpu_id', sa.Integer(), nullable=False, comment='cpus ID'),
    sa.Column('graphic_card_id', sa.Integer(), nullable=False, comment='graphic_cards ID'),
    sa.Column('gpu_request_name', sa.String(length=180), nullable=True),
    sa.Column('cpu_request_name', sa.String(length=180), nullable=True),
    sa.ForeignKeyConstraint(['cpu_id'], ['cpus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graphic_card_id'], ['graphic_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_pc_datas_id'), 'user_pc_datas', ['id'], unique=False)
    op.create_table('cost_services',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.String(length=10), nullable=False),
    sa.Column('computer_cost_range_id', sa.Integer(), nullable=False, comment='computer_cost_ranges ID'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='services ID'),
    sa.ForeignKeyConstraint(['computer_cost_range_id'], ['computer_cost_ranges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_services_id'), 'cost_services', ['id'], unique=False)
    op.create_table('pc_specification_programs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('average_fps', sa.String(length=12), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=False, comment='programs ID'),
    sa.Column('pc_specification_id', sa.Integer(), nullable=False, comment='pc_specifications ID'),
    sa.ForeignKeyConstraint(['pc_specification_id'], ['pc_specifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pc_specification_programs_id'), 'pc_specification_programs', ['id'], unique=False)
    op.create_table('purchase_requests',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('pc_specification_id', sa.Integer(), nullable=False, comment='pc_specifications ID'),
    sa.Column('billing_detail_id', sa.Integer(), nullable=False, comment='billing_details ID'),
    sa.Column('instant_user_id', sa.Integer(), nullable=False, comment='instant_users ID'),
    sa.ForeignKeyConstraint(['billing_detail_id'], ['billing_details.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instant_user_id'], ['instant_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pc_specification_id'], ['pc_specifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_requests_id'), 'purchase_requests', ['id'], unique=False)
    op.create_table('user_requests',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instant_user_id', sa.Integer(), nullable=False, comment='instant_users ID'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='services ID'),
    sa.Column('user_pc_data_id', sa.Integer(), nullable=True, comment='user_pc_datas ID'),
    sa.Column('user_laptop_data_id', sa.Integer(), nullable=True, comment='user_laptop_datas ID'),
    sa.ForeignKeyConstraint(['instant_user_id'], ['instant_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_laptop_data_id'], ['user_laptop_datas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_pc_data_id'], ['user_pc_datas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_requests_id'), 'user_requests', ['id'], unique=False)
    op.create_table('purchase_request_peripherals',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_request_id', sa.Integer(), nullable=False, comment='purchase_requests ID'),
    sa.Column('peripheral_id', sa.Integer(), nullable=False, comment='peripherals ID'),
    sa.ForeignKeyConstraint(['peripheral_id'], ['peripherals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_request_peripherals_id'), 'purchase_request_peripherals', ['id'], unique=False)
    op.create_table('purchase_request_programs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_request_id', sa.Integer(), nullable=False, comment='purchase_requests ID'),
    sa.Column('program_id', sa.Integer(), nullable=False, comment='programs ID'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_request_programs_id'), 'purchase_request_programs', ['id'], unique=False)
    op.create_table('user_request_defective_components',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_request_id', sa.Integer(), nullable=False, comment='user_requests ID'),
    sa.Column('type_defective_component_id', sa.Integer(), nullable=False, comment='type_defective_components ID'),
    sa.ForeignKeyConstraint(['type_defective_component_id'], ['type_defective_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_request_id'], ['user_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_request_defective_components_id'), 'user_request_defective_components', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_request_defective_components_id'), table_name='user_request_defective_components')
    op.drop_table('user_request_defective_components')
    op.drop_index(op.f('ix_purchase_request_programs_id'), table_name='purchase_request_programs')
    op.drop_table('purchase_request_programs')
    op.drop_index(op.f('ix_purchase_request_peripherals_id'), table_name='purchase_request_peripherals')
    op.drop_table('purchase_request_peripherals')
    op.drop_index(op.f('ix_user_requests_id'), table_name='user_requests')
    op.drop_table('user_requests')
    op.drop_index(op.f('ix_purchase_requests_id'), table_name='purchase_requests')
    op.drop_table('purchase_requests')
    op.drop_index(op.f('ix_pc_specification_programs_id'), table_name='pc_specification_programs')
    op.drop_table('pc_specification_programs')
    op.drop_index(op.f('ix_cost_services_id'), table_name='cost_services')
    op.drop_table('cost_services')
    op.drop_index(op.f('ix_user_pc_datas_id'), table_name='user_pc_datas')
    op.drop_table('user_pc_datas')
    op.drop_index(op.f('ix_user_laptop_datas_id'), table_name='user_laptop_datas')
    op.drop_table('user_laptop_datas')
    op.drop_index(op.f('ix_type_sub_services_id'), table_name='type_sub_services')
    op.drop_table('type_sub_services')
    op.drop_index(op.f('ix_speakers_id'), table_name='speakers')
    op.drop_table('speakers')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_psus_id'), table_name='psus')
    op.drop_table('psus')
    op.drop_index(op.f('ix_pc_specifications_id'), table_name='pc_specifications')
    op.drop_table('pc_specifications')
    op.drop_index(op.f('ix_mouses_id'), table_name='mouses')
    op.drop_table('mouses')
    op.drop_index(op.f('ix_monitors_id'), table_name='monitors')
    op.drop_table('monitors')
    op.drop_index(op.f('ix_kit_mouse_keyboards_id'), table_name='kit_mouse_keyboards')
    op.drop_table('kit_mouse_keyboards')
    op.drop_index(op.f('ix_keyboards_id'), table_name='keyboards')
    op.drop_table('keyboards')
    op.drop_index(op.f('ix_headsets_id'), table_name='headsets')
    op.drop_table('headsets')
    op.drop_index(op.f('ix_cost_range_defective_components_id'), table_name='cost_range_defective_components')
    op.drop_table('cost_range_defective_components')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_accessories_id'), table_name='accessories')
    op.drop_table('accessories')
    op.drop_index(op.f('ix_user_deliveries_id'), table_name='user_deliveries')
    op.drop_table('user_deliveries')
    op.drop_index(op.f('ix_type_defective_components_id'), table_name='type_defective_components')
    op.drop_table('type_defective_components')
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_peripherals_id'), table_name='peripherals')
    op.drop_table('peripherals')
    op.drop_table('oauth_tokens')
    op.drop_table('oauth_grants')
    op.drop_index(op.f('ix_model_laptops_id'), table_name='model_laptops')
    op.drop_table('model_laptops')
    op.drop_index(op.f('ix_minimal_type_services_id'), table_name='minimal_type_services')
    op.drop_table('minimal_type_services')
    op.drop_index(op.f('ix_graphic_cards_id'), table_name='graphic_cards')
    op.drop_table('graphic_cards')
    op.drop_index(op.f('ix_cpus_id'), table_name='cpus')
    op.drop_table('cpus')
    op.drop_index(op.f('ix_budget_pcs_id'), table_name='budget_pcs')
    op.drop_table('budget_pcs')
    op.drop_index(op.f('ix_billing_detail_natural_persons_id'), table_name='billing_detail_natural_persons')
    op.drop_table('billing_detail_natural_persons')
    op.drop_index(op.f('ix_billing_detail_companies_id'), table_name='billing_detail_companies')
    op.drop_table('billing_detail_companies')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_use_type_pcs_id'), table_name='use_type_pcs')
    op.drop_table('use_type_pcs')
    op.drop_index(op.f('ix_type_services_id'), table_name='type_services')
    op.drop_table('type_services')
    op.drop_index(op.f('ix_type_computers_id'), table_name='type_computers')
    op.drop_table('type_computers')
    op.drop_table('oauth_clients')
    op.drop_index(op.f('ix_instant_users_id'), table_name='instant_users')
    op.drop_table('instant_users')
    op.drop_index(op.f('ix_computer_cost_ranges_id'), table_name='computer_cost_ranges')
    op.drop_table('computer_cost_ranges')
    op.drop_index(op.f('ix_category_programs_id'), table_name='category_programs')
    op.drop_table('category_programs')
    op.drop_index(op.f('ix_category_peripherals_id'), table_name='category_peripherals')
    op.drop_table('category_peripherals')
    op.drop_index(op.f('ix_brand_laptops_id'), table_name='brand_laptops')
    op.drop_table('brand_laptops')
    op.drop_index(op.f('ix_brand_components_id'), table_name='brand_components')
    op.drop_table('brand_components')
    op.drop_index(op.f('ix_billing_details_id'), table_name='billing_details')
    op.drop_table('billing_details')
    # ### end Alembic commands ###
